---
# tasks file for roles/nginx
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Remove sites-available and sites-enabled if present
  file:
    path: "/etc/nginx/{{ item }}/"
    state: absent
  loop:
    - sites-available
    - sites-enabled
