---
# tasks file for roles/nginx
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Remove sites-available and sites-enabled if present
  file:
    path: "/etc/nginx/{{ item }}/"
    state: absent
  loop:
    - sites-available
    - sites-enabled

- name: Create locations directory
  file:
    path: /etc/nginx/locations
    state: directory

# in production this will already be handled by the rp role/server
- name: Copy template nginx config to server
  copy:
    src: dev_oracle.conf
    dest: /etc/nginx/conf.d/
  notify: reload nginx
