---
- name: Set up server
  hosts: main
  become: true
  become_user: root

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
        enabled: true

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Install packages required for ansible on the remote server
      apt:
        name:
          - python3-venv
          - python3-pip
          - acl
        state: present
    - name: Install other required packages
      apt:
        name: 
          - git
        state: present

  roles:
    - role: users
      tags:
        - users
        - setup
    - role: hardening
      tags:
        - hardening
        - setup
    - role: swap
      tags:
        - swap
        - setup
    - role: nginx
      tags: nginx
    - role: oracle
      tags: oracle

- name: Install rust and rust programs (as user running the playbook)
  hosts: main

  roles:
    - role: rust
      tags: rust

- name: Install python-related programs (some as user, some as root)
  hosts: main

  roles:
    - role: python
      tags: python

- name: Deploy traffic counts API
  hosts: main
  become: true

  roles:
    - role: traffic-counts-api
      tags: traffic-counts-api

- name: Install shell and terminal programs (as user running the playbook)
  hosts: main

  roles:
    - role: shell_terminal
      tags: shell_terminal
