---
# tasks file for python
- name: Install Python LSP and its mypy plugin
  pip:
    name:
      - python-lsp-server
      - pylsp-mypy
  become: true

- name: Install pipx
  pip:
    name: pipx
    extra_args: --user

- name: Install various python packages via pipx.
  block:
    - name: Check what's already installed by pipx.
      shell: "{{ pipx_path }}/pipx list"
      register: pipx_list

    - name: Install black via pipx
      shell: "{{ pipx_path }}/pipx install black"
      when: pipx_list.stdout.find("black") == -1
